#+title: Portfolio Development Class Syllabus
* Digital Art
** Submitting your work for review
**** Make a folder of your work
As well please submit your work in a folder with your name on it and include folders 
an
bg 
cd 
fg
an - for all animation work name the files an01.mp4 an02.mp4 an03.mp4 or an01.jpg an02.jpg
bg - for all background art work name the files bg01.jpg bg02.jpg bg03.jpg and so on
cd - for all character design work name the files cd01.jpg cd02.jpg cd03.jpg and so on
fg - for all figure drawing work and sketchbook name the files fg01.jpg fg02.jpg fg03.jpg and so on
sb - for all storyboard work name the files sb01.jpg sb02.jpg sb03.jpg or in pdf 
Make sure the file is .jpg
**** For Reviewing work 
***** MPV.io
For reviewing work MPV.io will be used, you don't need to download this program but I would recommend it for watching video and doing playback
Alternative: If you only have an iPAD Dropbox also works or the default program on ipad, mpv.io is good for playback because you can go frame by frame with keyboards
** - Dropbox
*** How to upload to Dropbox
1. Folder link is sent to you
2. go to your folder
3. import blender file
4. I get your blender file
5. I make notes on your folder
6. Updated folder is posted in the folder
7. You work more on the file
** - Open Broadcaster Software
*** How to use Open Broadcaster to share your screen on computer
1. Download Open Broadcaster Software
2. Share your desktop
3. Share 
4. Go to Zoom and share desktop through integrated Webcam
** - Install Blender
Download Blender 4.32 
https://www.blender.org/download/releases/4-3/
https://www.blender.org/download/demo-files/
--- there's also 3.6
*** TODO - specific version because we need to run the same version 
*** TODO - How to update keyboard shortcuts
* Animation Supplies
*** Traditional (meaning non-digital)
**** Animation Paper
For traditional animation Lightfoot is the main supplier of quality animation paper
the paper comes in different qualities
https://www.lightfootltd.com/catalog/animation-paper/12f-paper
but you could just get hole punched paper
****** About the paper
-  12 field is in reference to the size of the paper this is a good standard size of paper
-  17lb is fine paper it's basically the quality of printer paper but more transparent
-  20 lb is good better than printer paper
-  Ingram paper is almost too good it's kind of like vellum and is significantly pricier
-  Animation bond paper is even better but it's not 100% necessary unless you're doing very precise animation
  where you really need to erase. 
***** Plastic Peg Bar
the plastic peg bar is used to keep paper together using the wholes
  https://www.lightfootltd.com/content/acme-pegbar-plastic
***** Documenting your animation
if you were to animate with paper you would have to use a peg bar and hole punched paper along with a light table and then shoot your animation with whats called a downshooter or document camera or your phone
https://www.animationexploration.org/2020/03/15/diy-downshooter/
***** * a word on traditional animation
The main thing to consider in traditional is that you need to shoot your animation, each frame you have to take a photo of using a camera at the exact same spot and then you have to sequence them all together and composite them as a video file, so that will take around 10 minutes to an hour based on the complexity each time.
This doesn't mean that you have to shoot it every time to look at it you can flip it like a flipbook that's what animators in the past would do instead of shooting it every time, but you do have to film it in a well lit space and then time it out.
*** Digital  
Tools that can be used for digital animation
***** Procreate - 
Procreate can be used 
just make sure that you are animating on 24 frames per second in procreate and then setting the duration of each individual frame
***** Clip Studio Paint
- clip studio paint is a great software as it also allows for painting and illustration making and has a timeline for animation along with actions 
****** Using Clip Studio Paint for Animation
This is a good breakdown on how to use Clip Studio Paint for Animation
https://www.youtube.com/watch?v=3s88IcD2Q-8
***** TVPAINT
https://tvpaint.com/en/products/prices
- For classes you can use whichever program that you are comfortable with but for giving notes- the notes that I give will be done with TVPaint. You do not need TVPaint for the class though. I would recommend getting it at some point especially if you are accepted to CalArts because to my knowledge they do make you get a copy of it. 
***** Blender
- Blender has 2D and CG capabilities but it's kind of hard to use or get the hang of if you have any free time you might want to take a look at the program. It is only operational on computers though and does not have IPAD support
***** Photoshop
Photoshop might as well be used for character design notes or background design notes
* TVPAINT
** Navigating Drawings
*** Navigating Panels -
**** - Timeline 
 I'll try to keep this at the top 
**** (~) removes the timeline 
**** Main Panel - 
all the main tools are here
**** Tool Panel - 
this changes based on the tool that you use
**** Color Panel - 
for color I'll put this at the bottom and then make it bigger when I start coloring
*** Navigating Panels - Pt. 2
**** Line Smoothing - Only use if I'm doing Line Smoothing
**** Custom Brushes
I use pencil 9 usually
**** Handy Custom Panel
**** Sketch Panel 
*** Navigating Drawing
**** t - move backward - t
- instead of using the arrow keys have your keybrushes reachable in on the left side and the middle. This makes it easier to reach
**** y - move forward - y 
- y is to the left
**** q - move up a layer 
- reachable by pinkie finger so you can quickly use your pointer finger to move left and right and then use your pointer figure to move left and righte 
**** a - move down a layer
**** i - increment (insert new frame) i
- for a new drawing or keyframe hit i, this is s in blender so we will switch the over 
---- syllabus subject to change
